services:
  - type: web
    name: tsskwizi-backend
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: cd backend && python migrate_db.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
