services:
  - type: web
    name: tvet-quiz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:///quiz.db
      - key: SECRET_KEY
        generateValue: true